### Send POST request with json body
POST http://localhost:8080/projekt3/v1/users/create
Content-Type: application/json

{
  "username": "eliska",
  "firstName": "Eliska",
  "lastName": "Chylikova",
  "email": "eliska@gmail.com"
}
